#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/factory-run.sh [--task "..."] [--worktree-dir PATH] [--agent NAME] [--agent-cmd CMD] [--test-cmd CMD] [--cleanup] [--create-pr] [--ci-max-attempts N] [--help]

Phase-1 POC:
- create a git worktree per task
- write the task into the worktree
- run a coding agent CLI in the worktree (codex/claude/custom)
- run tests and report pass/fail
- optionally push + create PR, then poll CI checks and self-heal up to 3 attempts

Defaults:
- task: hardcoded POC task
- agent: codex
- test command: npm test
USAGE
}

repo_root=""
worktree_dir=""
cleanup="false"
task=""
agent_name="codex"
agent_cmd=""
test_cmd="npm test"
create_pr="false"
ci_max_attempts=3

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h)
      usage
      exit 0
      ;;
    --task)
      task="${2:-}"
      shift 2
      ;;
    --worktree-dir)
      worktree_dir="${2:-}"
      shift 2
      ;;
    --agent)
      agent_name="${2:-}"
      shift 2
      ;;
    --agent-cmd)
      agent_cmd="${2:-}"
      shift 2
      ;;
    --test-cmd)
      test_cmd="${2:-}"
      shift 2
      ;;
    --cleanup)
      cleanup="true"
      shift
      ;;
    --create-pr)
      create_pr="true"
      shift
      ;;
    --ci-max-attempts)
      ci_max_attempts="${2:-}"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

repo_root="$(git -C "$(dirname "$0")/.." rev-parse --show-toplevel)"
if [[ -z "$repo_root" ]]; then
  echo "Failed to resolve repo root." >&2
  exit 1
fi

if [[ -z "$task" ]]; then
  task="POC task: run agent CLI in isolated worktree and execute tests."
fi

if ! [[ "$ci_max_attempts" =~ ^[0-9]+$ ]] || [[ "$ci_max_attempts" -lt 1 ]] || [[ "$ci_max_attempts" -gt 3 ]]; then
  echo "--ci-max-attempts must be an integer between 1 and 3" >&2
  exit 2
fi

if [[ -z "$worktree_dir" ]]; then
  worktree_dir="$repo_root/.worktrees"
fi

if [[ -z "$agent_cmd" ]]; then
  case "$agent_name" in
    codex)
      agent_cmd='codex "Read TASK.md and implement the requested change in this worktree. Run tests and summarize outcomes in AGENT-REPORT.md."'
      ;;
    claude)
      agent_cmd='claude "Read TASK.md and implement the requested change in this worktree. Run tests and summarize outcomes in AGENT-REPORT.md."'
      ;;
    *)
      echo "Unknown --agent '$agent_name'. Use codex, claude, or provide --agent-cmd." >&2
      exit 2
      ;;
  esac
fi

mkdir -p "$worktree_dir"

stamp="$(date +%Y%m%d-%H%M%S)"
branch="poc/task-$stamp"
worktree_path="$worktree_dir/$branch"
status_file="$worktree_dir/factory-run-$stamp.status"
pr_url=""
ci_result="not_run"
ci_attempts=0
ci_last_error=""

if [[ -e "$worktree_path" ]]; then
  echo "Worktree path already exists: $worktree_path" >&2
  exit 1
fi

cleanup_worktree() {
  if [[ "$cleanup" == "true" && -d "$worktree_path" ]]; then
    git -C "$repo_root" worktree remove "$worktree_path" >/dev/null 2>&1 || true
  fi
}
trap cleanup_worktree EXIT

git -C "$repo_root" worktree add -b "$branch" "$worktree_path" >/dev/null

echo "$task" >"$worktree_path/TASK.md"
echo "[factory-run] task written to $worktree_path/TASK.md"

echo "[factory-run] running agent command ($agent_name): $agent_cmd"
agent_rc=0
if ! (
  cd "$worktree_path"
  bash -lc "$agent_cmd"
); then
  agent_rc=$?
fi

echo "[factory-run] running test command: $test_cmd"
test_rc=0
if ! (
  cd "$worktree_path"
  bash -lc "$test_cmd"
); then
  test_rc=$?
fi

result="pass"
if [[ "$agent_rc" -ne 0 || "$test_rc" -ne 0 ]]; then
  result="fail"
fi

cat >"$status_file" <<STATUS
branch=$branch
worktree=$worktree_path
agent=$agent_name
agent_rc=$agent_rc
test_cmd=$test_cmd
test_rc=$test_rc
result=$result
timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
STATUS

echo "[factory-run] status written to $status_file"

echo "[factory-run] git status for worktree:"
GIT_DIR="$worktree_path/.git" git -C "$worktree_path" status -sb

echo "[factory-run] done ($result)"

if [[ "$result" == "pass" && "$create_pr" == "true" ]]; then
  echo "[factory-run] creating PR and polling CI checks"
  pushd "$worktree_path" >/dev/null

  if ! git remote get-url origin >/dev/null 2>&1; then
    ci_result="skipped"
    ci_last_error="missing git origin remote"
    echo "[factory-run] skipping PR: $ci_last_error"
  else
    git add -A
    if ! git diff --cached --quiet; then
      git commit -m "feat: complete factory task $stamp" >/dev/null
    fi

    if git push -u origin "$branch" >/dev/null 2>&1; then
      pr_title="Factory task $stamp"
      pr_body="Automated change generated by scripts/factory-run.sh"
      if gh_out="$(gh pr create --title "$pr_title" --body "$pr_body" --base main --head "$branch" 2>/dev/null)"; then
        pr_url="$(printf '%s' "$gh_out" | tail -n 1)"
        ci_result="pending"

        while [[ "$ci_attempts" -lt "$ci_max_attempts" ]]; do
          ci_attempts=$((ci_attempts + 1))
          if checks_out="$(gh pr checks "$pr_url" 2>&1)"; then
            if printf '%s' "$checks_out" | grep -q 'fail'; then
              ci_last_error="ci checks reported failure"
              if [[ "$ci_attempts" -lt "$ci_max_attempts" ]]; then
                echo "[factory-run] CI failed (attempt $ci_attempts/$ci_max_attempts), retrying tests and pushing"
                if bash -lc "$test_cmd" >/dev/null 2>&1 && git push >/dev/null 2>&1; then
                  sleep 5
                  continue
                else
                  ci_last_error="self-fix attempt failed"
                fi
              fi
              ci_result="failed"
              break
            fi

            if printf '%s' "$checks_out" | grep -Eq '(pass|success)'; then
              ci_result="passed"
              break
            fi

            sleep 5
          else
            ci_last_error="gh pr checks failed"
            ci_result="failed"
            break
          fi
        done

        if [[ "$ci_result" == "pending" ]]; then
          ci_result="failed"
          ci_last_error="ci checks did not reach pass state"
        fi
      else
        ci_result="failed"
        ci_last_error="gh pr create failed"
      fi
    else
      ci_result="failed"
      ci_last_error="git push failed"
    fi
  fi

  popd >/dev/null
fi

cat >>"$status_file" <<STATUS
create_pr=$create_pr
pr_url=$pr_url
ci_attempts=$ci_attempts
ci_result=$ci_result
ci_last_error=$ci_last_error
STATUS

if [[ "$result" != "pass" ]]; then
  exit 1
fi

if [[ "$create_pr" == "true" && "$ci_result" != "passed" && "$ci_result" != "skipped" ]]; then
  echo "[factory-run] escalation: CI did not pass after $ci_attempts attempt(s)."
  exit 1
fi
