/**
 * Critic Gate — Phase 5 POC
 * Deterministic validation layer before push/PR creation
 * Blocks push/PR unless green, or explicitly overridden with "force" mode
 */

class CriticGate {
  constructor(taskManager) {
    this.taskManager = taskManager;
    this.requiredChecks = ['lint', 'test']; // typecheck optional for now
  }

  /**
   * Evaluate if a task is ready for push/PR
   * @param {Object} task - task record with validationResult
   * @param {Object} options - { forceMode: boolean }
   * @returns {Object} - { canPush, reason, checks }
   */
  evaluate(task, options = {}) {
    const { forceMode = false } = options;
    const checks = {};
    let allPassed = true;

    console.log(`[CriticGate] Evaluating task ${task.id} (forceMode: ${forceMode})`);

    if (!task.validationResult) {
      return {
        canPush: false,
        reason: 'No validation result attached to task',
        checks: {}
      };
    }

    // Check each required validation
    for (const checkName of this.requiredChecks) {
      const step = task.validationResult.steps?.find(s => s.name === checkName);
      
      if (!step) {
        checks[checkName] = { status: 'missing', error: `${checkName} step not found` };
        allPassed = false;
      } else if (!step.success) {
        checks[checkName] = { status: 'failed', error: step.error };
        allPassed = false;
      } else {
        checks[checkName] = { status: 'passed' };
      }
    }

    // Determine if push is allowed
    let canPush = allPassed;
    let reason = allPassed ? 'All checks passed' : 'Some checks failed';

    if (!allPassed && forceMode) {
      canPush = true;
      reason = 'Force mode enabled (override)';
      console.warn(`[CriticGate] FORCE MODE: Task ${task.id} approved despite failures`);
    }

    return {
      canPush,
      reason,
      checks,
      forceMode,
      evaluatedAt: new Date().toISOString()
    };
  }

  /**
   * Log force mode override to task record
   */
  logForceOverride(taskId, reason) {
    const task = this.taskManager.get(taskId);
    if (!task) throw new Error(`Task ${taskId} not found`);

    if (!task.forceOverrides) task.forceOverrides = [];
    task.forceOverrides.push({
      reason,
      timestamp: new Date().toISOString()
    });

    this.taskManager.persistQueue();
    console.log(`[CriticGate] Logged force override for task ${taskId}: ${reason}`);
  }

  /**
   * Generate PR body with validation results
   */
  generatePRBody(task, evaluation) {
    const checksSummary = Object.entries(evaluation.checks)
      .map(([name, result]) => `- **${name}**: ${result.status}${result.error ? ` (${result.error})` : ''}`)
      .join('\n');

    const forceNotice = evaluation.forceMode ? '\n⚠️ **FORCE MODE**: This PR was approved despite validation failures. Review carefully.\n' : '';

    return `## Task: ${task.title}

${task.description}

### Validation Results
${checksSummary}

${forceNotice}

### Task ID
\`${task.id}\`

### Parent Task
${task.parentTaskId ? `\`${task.parentTaskId}\`` : 'N/A'}

---
*Generated by Coding Factory Phase 5*`;
  }
}

// ESM default export — enables: import Factory from './critic-gate.js'
export default CriticGate;
export { CriticGate };